apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-watch
spec:
  selector:
    matchLabels:
      app: api-watch
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: api-watch
        aadpodidbinding: bind
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      volumes:
      - name: shared-data
        hostPath:
          path: /shared-data
      containers:
      - name: api-watch
        image: ss104301/watch-ns-py:latest
        resources:
          requests:
            memory: "80Mi"
          limits:
            memory: "250Mi"
      - name: tcpdump
        image: corfr/tcpdump
        command:
        - "/usr/sbin/tcpdump"
        - "-i"
        - "any"
        - "-nn"
        - "-w"
        - "/shared-data/cap-pod.pcap"
        resources:
          requests:
            memory: "250Mi"
          limits:
            memory: "1Gi"
        volumeMounts:
        - name: shared-data
          mountPath: /shared-data
